default: &default
  adapter: trilogy
  pool: 5
  timeout: 5000
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: kev_cool_development

test:
  <<: *default
  database: kev_cool_test
