development:
  secret_key_base: ac3024dd9ed108663e4a4d6637a617c76fdfb9fc99d3ad4846d3fba95875b587c6c06b9cc83cf2c76500e146970065bf0e789e8c131dea4b4f18f5a7798f0d2f
  sidekiq_admin_username: sidekiq-username-development
  sidekiq_admin_password: sidekiq-password-development
  improvmx_username: improvmx-username-development
  improvmx_password: improvmx-password-development
  email_test_recipient: test@example.com

test:
  secret_key_base: 9b7d9af479fef7d483cb4d2150bee37ede093327fd996b72d7676a43bed21fac0d34ec4fec05884649b085edfb6b078a0778e7d6494ae677eb0d416fab2e2f9a
  sidekiq_admin_username: sidekiq-username-test
  sidekiq_admin_password: sidekiq-password-test
  improvmx_username: improvmx-username-test
  improvmx_password: improvmx-password-test
  email_test_recipient: test@example.com
